version: "3.8"
services:
  api:
    container_name: api
    build: .
    ports:
      - "3000:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
